# Generated by Django 2.2.16 on 2022-10-04 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название ингредиента', max_length=200, unique=True, verbose_name='название ингредиента')),
                ('unit', models.CharField(help_text='введите название ингредиента', max_length=10, verbose_name='название ингредиента')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название рецепта', max_length=200, unique=True, verbose_name='название рецепта')),
                ('image', models.ImageField(blank=True, upload_to='recipes/', verbose_name='Картинка')),
                ('description', models.TextField(help_text='введите текст описания ', verbose_name='текст описания')),
                ('time', models.PositiveIntegerField(help_text='введите количество', verbose_name='количество')),
                ('author', models.ForeignKey(help_text='введите автора', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('ingredient', models.ManyToManyField(help_text='введите ингредиент', to='recipe.Ingredient', verbose_name='ингредиент')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название тега', max_length=200, verbose_name='название тега')),
                ('slug', models.SlugField(help_text='введите название тега', max_length=200, unique=True, verbose_name='название тега')),
                ('color', models.CharField(help_text='введите название тега', max_length=7, verbose_name='название тега')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='введите название рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to='recipe.Recipe', verbose_name='название рецепта')),
                ('user', models.ForeignKey(help_text='ссылка на объект пользователя, который подписывается', on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(help_text='введите тэг', to='recipe.Tag', verbose_name='тэг'),
        ),
        migrations.CreateModel(
            name='Ingredient_amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='введите количество', verbose_name='количество')),
                ('ingredient', models.ForeignKey(help_text='введите название ингредиента', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_amount', to='recipe.Ingredient', verbose_name='название ингредиента')),
                ('recipe', models.ForeignKey(help_text='введите название рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipe.Recipe', verbose_name='название рецепта')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(help_text='ссылка на объект пользователя, на которого подписываются', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user', models.ForeignKey(help_text='ссылка на объект пользователя, который подписывается', on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(help_text='введите название рецепта', on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipe.Recipe', verbose_name='название рецепта')),
                ('user', models.ForeignKey(help_text='ссылка на объект пользователя, который подписывается', on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
