# Generated by Django 2.2.16 on 2022-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='введите название ингредиента', max_length=200, verbose_name='название ингредиента'),
        ),
    ]
