# Generated by Django 2.2.16 on 2022-10-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20221017_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_amount',
            name='ingredient',
            field=models.ForeignKey(help_text='введите название ингредиента', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredient', to='recipe.Ingredient', verbose_name='название ингредиента'),
        ),
    ]
