# Generated by Django 2.2.16 on 2022-10-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20221018_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='введите время приготовления', verbose_name='время приготовления'),
        ),
    ]
