# Generated by Django 2.2.16 on 2022-10-18 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_auto_20221018_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_amount',
            old_name='quantity',
            new_name='amount',
        ),
    ]
