# Generated by Django 2.2.16 on 2022-10-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20221020_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
